services:
  mysql:
    image: ${MYSQL_VERSION}
    container_name: dev_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - "${LOCAL_LISTEN_ADDR}:${HOST_PORT_MYSQL}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network   # Attach to the shared network
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p$$MYSQL_ROOT_PASS -e 'SELECT 1;'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dev_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${HOST_PORT_MYSQL}
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      #ARBITRARY: 0
    ports:
      - "${LOCAL_LISTEN_ADDR}:8090:80"
    networks:
      - shared-network
    depends_on:
      mysql:
        condition: service_healthy

  postgres:
    image: ${PGSQL_VERSION}
    container_name: dev_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGSQL_ROOT_USER}
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASS}
      POSTGRES_HOST_AUTH_METHOD: ${PGSQL_HOST_AUTH_METHOD:-trust}
      POSTGRES_DB: ${PGSQL_DATABASE}
    ports:
      - "${LOCAL_LISTEN_ADDR}:${HOST_PORT_PGSQL}:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - shared-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${PGSQL_ROOT_USER:-postgres} -d ${PGSQL_DATABASE:-testdb}
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_ROOT_PASS}
    ports:
      - "${LOCAL_LISTEN_ADDR}:${HOST_PORT_MSSQL}:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_ROOT_PASS\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  mongodb:
    image: ${MONGODB_VERSION}
    container_name: dev_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASS}
    ports:
      - "${LOCAL_LISTEN_ADDR}:${HOST_PORT_MONGODB}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  pg_data:
  mssql_data:
  mongo_data:

networks:
  shared-network:
    external: true
    name: shared_ext_net